version: '3'

services:
  db:
    container_name: 'health-db'
    image: postgres:14.5
    restart: always
    ports:
      - '9998:5432'
    volumes:
      - ./postgres_dev:/var/lib/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootpass
      - POSTGRES_DB=health
